***INCLUDE LSEU0F02 .
FORM SAFETY_CHECK USING NAME STATUS O_TYPE CHANGING VALUE(RCODE).
  DATA: FIRST_LINE(70),
        SECOND_LINE(70),
        ANSWER.

  CASE O_TYPE.
    WHEN 'DSTA'.
      CLEAR SCR_RETURN.
      RSMPE-PROGRAM = NAME.
      RSMPE-STATUS  = STATUS.
      CALL SCREEN 120 STARTING AT 10 5.
      IF SCR_RETURN NE CON_CANCEL. ANSWER = 'J'. ENDIF.
    WHEN 'DALL'.
      FIRST_LINE  = TEXT-046.
      SECOND_LINE = TEXT-047.
      REPLACE '&' WITH NAME INTO SECOND_LINE.
      CALL FUNCTION 'POPUP_TO_CONFIRM_STEP'
           EXPORTING
                DEFAULTOPTION = 'N'
                TEXTLINE1 = FIRST_LINE
                TEXTLINE2 = SECOND_LINE
                TITEL = TEXT-048
           IMPORTING
                ANSWER = ANSWER.
    WHEN 'DMEN'.
      FIRST_LINE  = TEXT-052.
      SECOND_LINE = TEXT-053.
      REPLACE '&' WITH NAME   INTO SECOND_LINE.
      CALL FUNCTION 'POPUP_TO_CONFIRM_STEP'
           EXPORTING
                DEFAULTOPTION = 'N'
                TEXTLINE1 = FIRST_LINE
                TEXTLINE2 = SECOND_LINE
                TITEL = TEXT-054
           IMPORTING
                ANSWER = ANSWER.
  ENDCASE.
  IF ANSWER = 'J'. RCODE = CON_CONTINUE. ENDIF.
ENDFORM.
